name       : cutegram
version    : 2.7.1
release    : 4
source     :
    - https://github.com/Aseman-Land/Cutegram/archive/v2.7.1-stable.tar.gz : f1cfc6bd3a1d33c2348f23ea43d923419b33576059791a071f2780db11059cf4
    - https://github.com/Aseman-Land/aseman-qt-tools/archive/v1.0.0-stable.tar.gz : 44ad93a205921ed920b7dbcca1ae4d8150d001b06d6f8f01e46da02cc607ece2
license    : GPL-3.0
component  : network.im
summary    : Cutegram is a telegram client by Aseman Land.
description: |
    Cutegram is a telegram client by Aseman Land.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(Qt5Core)
    - gstreamer-1.0-plugins-good
    - libqtelegram-ae-devel
    - qtkeychain-devel
    - telegramqml-devel
setup      : |
    tar xf $sources/v1.0.0-stable.tar.gz -C $workdir/Cutegram/asemantools --strip-components=1
    mkdir build
build      : |
    cd build
    qmake -r .. PREFIX=$installdir/usr
    %make
install    : |
    cd build
    %make_install