name       : cutegram
version    : 2.7.1
release    : 1
source     :
    - https://github.com/Aseman-Land/Cutegram/archive/v2.7.1-stable.tar.gz : f1cfc6bd3a1d33c2348f23ea43d923419b33576059791a071f2780db11059cf4
license    : GPL-3.0
summary    : Cutegram is a telegram client by Aseman Land.
description: |
    Cutegram is a telegram client by Aseman Land.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(Qt5Core)
    - git
    - gstreamer-1.0-plugins-good
    - libqtelegram-ae-devel
    - telegramqml-devel
setup      : |
    git clone https://github.com/Aseman-Land/aseman-qt-tools.git Cutegram/asemantools
    mkdir build
build      : |
    cd build
    qmake -r .. PREFIX=$installdir/usr
    %make
install    : |
    cd build
    %make_install
